// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/aesingflow/config.proto

package aesingflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Server                        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	ServerPort                    uint32                 `protobuf:"varint,2,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	Token                         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	ServerName                    string                 `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	CaFile                        string                 `protobuf:"bytes,5,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	MaxStreams                    uint32                 `protobuf:"varint,6,opt,name=max_streams,json=maxStreams,proto3" json:"max_streams,omitempty"`
	BrutalBps                     uint64                 `protobuf:"varint,7,opt,name=brutal_bps,json=brutalBps,proto3" json:"brutal_bps,omitempty"`
	DisableBrutal                 bool                   `protobuf:"varint,8,opt,name=disable_brutal,json=disableBrutal,proto3" json:"disable_brutal,omitempty"`
	BrutalDisableLossCompensation bool                   `protobuf:"varint,9,opt,name=brutal_disable_loss_compensation,json=brutalDisableLossCompensation,proto3" json:"brutal_disable_loss_compensation,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_aesingflow_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_aesingflow_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_aesingflow_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Config) GetServerPort() uint32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *Config) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Config) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Config) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *Config) GetMaxStreams() uint32 {
	if x != nil {
		return x.MaxStreams
	}
	return 0
}

func (x *Config) GetBrutalBps() uint64 {
	if x != nil {
		return x.BrutalBps
	}
	return 0
}

func (x *Config) GetDisableBrutal() bool {
	if x != nil {
		return x.DisableBrutal
	}
	return false
}

func (x *Config) GetBrutalDisableLossCompensation() bool {
	if x != nil {
		return x.BrutalDisableLossCompensation
	}
	return false
}

var File_proxy_aesingflow_config_proto protoreflect.FileDescriptor

const file_proxy_aesingflow_config_proto_rawDesc = "" +
	"\n" +
	"\x1dproxy/aesingflow/config.proto\x12\x15xray.proxy.aesingflow\"\xc1\x02\n" +
	"\x06Config\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1f\n" +
	"\vserver_port\x18\x02 \x01(\rR\n" +
	"serverPort\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1f\n" +
	"\vserver_name\x18\x04 \x01(\tR\n" +
	"serverName\x12\x17\n" +
	"\aca_file\x18\x05 \x01(\tR\x06caFile\x12\x1f\n" +
	"\vmax_streams\x18\x06 \x01(\rR\n" +
	"maxStreams\x12\x1d\n" +
	"\n" +
	"brutal_bps\x18\a \x01(\x04R\tbrutalBps\x12%\n" +
	"\x0edisable_brutal\x18\b \x01(\bR\rdisableBrutal\x12G\n" +
	" brutal_disable_loss_compensation\x18\t \x01(\bR\x1dbrutalDisableLossCompensationBa\n" +
	"\x19com.xray.proxy.aesingflowP\x01Z*github.com/xtls/xray-core/proxy/aesingflow\xaa\x02\x15Xray.Proxy.Aesingflowb\x06proto3"

var (
	file_proxy_aesingflow_config_proto_rawDescOnce sync.Once
	file_proxy_aesingflow_config_proto_rawDescData []byte
)

func file_proxy_aesingflow_config_proto_rawDescGZIP() []byte {
	file_proxy_aesingflow_config_proto_rawDescOnce.Do(func() {
		file_proxy_aesingflow_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_aesingflow_config_proto_rawDesc), len(file_proxy_aesingflow_config_proto_rawDesc)))
	})
	return file_proxy_aesingflow_config_proto_rawDescData
}

var file_proxy_aesingflow_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_aesingflow_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.proxy.aesingflow.Config
}
var file_proxy_aesingflow_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_aesingflow_config_proto_init() }
func file_proxy_aesingflow_config_proto_init() {
	if File_proxy_aesingflow_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_aesingflow_config_proto_rawDesc), len(file_proxy_aesingflow_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_aesingflow_config_proto_goTypes,
		DependencyIndexes: file_proxy_aesingflow_config_proto_depIdxs,
		MessageInfos:      file_proxy_aesingflow_config_proto_msgTypes,
	}.Build()
	File_proxy_aesingflow_config_proto = out.File
	file_proxy_aesingflow_config_proto_goTypes = nil
	file_proxy_aesingflow_config_proto_depIdxs = nil
}
